### ISSUE TITLE
mr. fantastic - skinned mesh / bones

### ISSUE THREAD

**Issue by ghost** [HelloKitty/RS317.Sharp#5]
![image](https://user-images.githubusercontent.com/37026425/60990325-65d2f980-a305-11e9-869c-ede396e3bb12.png)
the win forms build:
any pointers where to look to fix this?
I still wonder if my cache is wrong, I had to source it piece by piece

**Comment by HelloKitty** [comment]
@communityus The best way to know if this is a Rs317.Sharp client problem is to run like a 317 Moparscape client, or another 317 client, to see if it also has the same problem.

If you open a public server for me to connect to, I can connect with both the winforms client and a moparscape client to see if it's an issue with this project or just the server you're running.

**Comment by HelloKitty** [comment]
It would also help to know what NPC that is, where it is and etc. The test server I downloaded doesn't have much on it, but maybe that NPC is there.

**Comment by HelloKitty** [comment]
Has this been resolved?

**Comment by ghost** [comment]
Since I am revisiting this project. No it doesn't look like it is fixed. This is all part of the 
Document Server: https://github.com/HelloKitty/RS317.Sharp/issues/11
Recommend a 317 server: https://github.com/HelloKitty/RS317.Sharp/issues/2
issues.
![image](https://user-images.githubusercontent.com/37026425/76140486-284f7900-6018-11ea-82d0-d2dbaa64f03c.png)

Thankfully, I had solved this way back when using the No-Doze server which (I assume during my research at that time was the closest to the server you mentioned using "shardrev") as that was the root folder name I put it in. Thank God I keep halfway decent notes lol. 

Anyways, even though today I was able to roll back to that old old commit and get the win forms working - it certainly doesn't work with present main branch. So not sure how to proceed until we get more information.

So I am stuck here:
https://github.com/HelloKitty/RS317.Sharp/issues/9#issuecomment-596056035

**Comment by ghost** [comment]
Its related to the player not having animations played. That is why the bones are all weird. If I click any animation - even in Unity the player looks normal. So do all the NPCs.
![image](https://user-images.githubusercontent.com/37026425/76143331-d4eb2400-6033-11ea-9cab-758a1760fab5.png)
Tested on: https://github.com/HelloKitty/RS317.Sharp/tree/db5e5b662769edf5c3ff23006e7f954baf136901

**Comment by ghost** [comment]
Closing this out.
https://github.com/HelloKitty/RS317.Sharp/issues/6
