### ISSUE TITLE
License Clarity.

### ISSUE THREAD

**Issue by ghost** [HelloKitty/RS317.Sharp#6]
Before I got too far I wanted to confirm all your code was MIT. I saw this on readme, and wanted to clarify. (Below) As the repo itself is MIT, and the fork before MIT.

> Applicable licensing referenced in 317Refactor and additional work/changes done licensed under a modified AGPL license.

**Comment by HelloKitty** [comment]
The licensing is complicated. So, it's a fork of 317Refactor which means 317Refactor's MIT license which you can see here: https://github.com/HelloKitty/RS317.Sharp/blob/master/LICENSE is in effect for whatever percentage of the repository can be attributed to the renaming/refactoring work by 317Refactor.

The additional code, changes and the result/process of the translation from Java to C# is licensed by me under AGPL https://www.gnu.org/licenses/agpl-3.0.en.html

```The GNU Affero General Public License is a free, copyleft license for software and other kinds of works, specifically designed to ensure cooperation with the community in the case of network server software.```

It's a license specifically designed by GNU for opensource software based around networked software, and it's defining requirement is that you keep your work opensource if you modify it. This is to ensure that people using the project actually give value back to it in some way.

While MIT is good, it means someone could fork/clone the project and keep it closed source and contribute back no value to the project or community.

That is why I opt for AGPL.

**Comment by HelloKitty** [comment]
I made a commit to clarify this, but I am unable to push at this time.

Do you not like the AGPL?

**Comment by HelloKitty** [comment]
MIT has no requirement to license derivatives or forks under the same license so long as you retain the requirements of the MIT license. GPL is a viable replacement, because MIT is a subset of the GPL.

**Comment by HelloKitty** [comment]
The reason the Runescape emulation scene is so far behind World of Warcraft, even though they got half a decade's headstart, is because there is no actually community. Nothing is opensource, and nobody contributes anything back.

Unlike WoW which has TrinityCore, Mangos and others. Some of the largest projects on Github, emulators for WoW. Another reason I choose the AGPL, it benefits the community and the players on RSPS themselves to have this sort of stuff opensource.

**Comment by ghost** [comment]
Licensing always a hot topic. I prefer to trust the people to give back, not pressure them through licensing. I can't use anything gpl because at some point I will need for convenience to link it with code I don't have source for. If I do something for FSF I favor dual license one mit/apache/bsd or similar less restrictive and then usually gpl v2.

**Comment by HelloKitty** [comment]
AGPL doesn't prevent you from linking code you don't have the source for. AGPL only applies when you're linking TO the AGPL worked. It doesn't require you to distribute anything but your changes to the work itself, it's not a viral license and it doesn't require you to distribute anything but the modified work.

I can understand the desire for MIT but people don't contribute back, they never do. Billion dollar companies don't, unless it's in their interest. The unfortunate situation gave rise to the AGPL which is basically: "If you use the software, makes changes or improves then you are required to share."

**Comment by HelloKitty** [comment]
I hope you'll continue to use the project but I want to encourage a community like the WoW emulation community, where people work together and give back to the major projects for the benefit of other developers and in the end the players.

The Runescape emulation scene could be 10 years ahead. I've been watching it from the outside for some time now, it's disappointing =(.

**Comment by ghost** [comment]
The only way I can contribute is if you allow us to keep the MIT license on our fork and continue a MIT branch in line with dual license discussed above (or apache/bsd/anything less restrictive and less pressuring) we would be happy to comply with your wish not use anyone else's code that contributes to your codebase. I would just like to use your code to date under MIT as was the parent, I will still contribute back here and let it be licensed AGPL and then keep our codebase MIT and we can clearly state this... if something like this is doable I will be happy to continue. Otherwise, I just don't have the time at present to contribute to a only AGPL codebase maybe when I retire ;-) the reason is I need to be able to justify in a court of law if I have to that I was allowed to learn from a codebase or come up with a derivative work based on anothers idea. This can't be done on GPL, once there locked in. This is why I think the way to go is dual license. Keep the flame alive for FSF but also offer unrestrictive freedom too. Win / Win.

**Comment by HelloKitty** [comment]
It won't benefit the project or the community. It's why Runescape emulation is still at square 2 when projects like GPL 2.0 https://github.com/trinitycore/trinitycore and AGPL https://github.com/azerothcore/azerothcore-wotlk have had so much success. It's why Runescape emulation is a joke compared to WoW emulation.

I don't really want to continue that. Helping people create for-profit and closed source projects in the RSPS community is not one of my goals. The repository has always been AGPL, I pretty much exclusively write AGPL software. If you want an MIT licensed 317 client, then https://github.com/Jameskmonger/317refactor is MIT licensed, and it's where the MIT license you saw in the repository came from, not related to me at all. It even mentions Copyright (c) 2014 Jameskmonger.

I am here to create opensource software and an opensource C# emulation community across multiple MMORPGs. I'm not here to help the RSPS scene create more closed source and/or for-profit servers.

**Comment by ghost** [comment]
To give the subject balanced perspective, since it was reopened I assume for visibility. Bitcoin is MIT. It gets contributed back to. I think the license plays a role in who you want to help. AGPL certainly helps the runescape community, but locks it. MIT would help all game dev's on all projects is the point. Not trying to get you to change your mind, just stating the counter points plainly since it was reopened for visibility. There are many other open source projects that work as MIT Godot engine, Xenko, etc. In my view MIT/BSD/Apache invites collab from everyone, GPL is for specific use case and readers should know it is treated like a contract. So go in as if you signed a contract and ready to go to court. (Take it serious, as GPL community does.)

**Comment by ghost** [comment]
I saw your sentiment here: https://www.rune-server.ee/runescape-development/rs2-client/downloads/686787-rs317-sharp-working-c-net-port-317refactor-2.html
in a convo about licensing.
"It's really disappointing that this is all anyone posts about."

The thing is, the license is the most important thing to consider when putting time into a project.  Why spend a bunch of time on something that I may not have a license to use in a way I want. To me this is what liberty should mean. Isn't that what AGPL is all about, giving liberty with restrictions clearly stated.
![image](https://user-images.githubusercontent.com/37026425/76210113-0ea16380-61c9-11ea-83e4-e252d7a7dade.png)
Major makes a good point here. It is so good of a point, I've come to realize this project needs to be separated out into different pieces.
First the deob code needs to be removed from anything claiming AGPL.
AGPL can't be in with closed source Unity so that needs to be changed to LGPL.
If interested in allowing IL2CPP that becomes an issue for LGPL see here:
https://github.com/mcs-sdk/mcs/issues/4
So an exemption would need to be added:

> As a special exception, the copyright holders of this library give you
> permission to link this library with independent modules to produce an
> executable, regardless of the license terms of these independent modules,
> and to copy and distribute the resulting executable under terms of your
> choice, provided that you also meet, for each linked independent module,
> the terms and conditions of the license of that module. An independent
> module is a module which is not derived from or based on this library.
> If you modify this library, you must extend this exception to your
> version of the library.

Then things need to be looked at to check compatibility.
LGPL is AGPL compatible (but not the other way around)

It seems with the GladMMO library and so on you truly want to make a go of this. I recommend not once but maybe as many as 3x getting hyper focused on licensing over the next 6 months and be sure what you want to do makes sense with the licensing. To me looking at a lot of your projects. A GPLv2 would make more sense in several areas - and then some LGPL with exemptions in parts. Slapping AGPL on things, doesn't always make them AGPL if they aren't compatible and could result in the work being removed. That is why a lot of folks that don't want to spend the time doing all this licensing crud opt of less restrictive licensing. Remember the GPL stuff in general is designed to put pressure on people to conform to the GPL.

I take your point that the GPL also means people have to contribute back their code. If this is the only reason for selecting the GPL, there are other licenses that also require that with less restrictions that may be a better fit. like the QTPL http://opensource.org/licenses/qtpl.php
https://github.com/raduprv/Eternal-Lands/blob/master/eternal_lands_license.txt 

Lastly, it is a matter of trust. When I first saw the stuff about licensing I had assumed the deob code was removed as that can't be done with AGPL. When i was looking into the RSA I found the deob code alive and well in there.

**Comment by HelloKitty** [comment]
I am not interested in discussing the licensing further. Don't use the project if you don't want to, anything I've written is under AGPL and that includes the translation from Java to C#. Can I license that under AGPL? That's for a court to decide.
